# To manually find version numbers, use
# https://linkie.shedaniel.dev/dependencies
# https://parchmentmc.org/docs/getting-started for version table

[libraries]
fabricApi = "net.fabricmc.fabric-api:fabric-api:0.139.5+1.21.11"
fabricLoader = "net.fabricmc:fabric-loader:0.18.2"
lombok = "org.projectlombok:lombok:1.18.42"
minecraft = "com.mojang:minecraft:1.21.11"
parchment = "org.parchmentmc.data:parchment-1.21.10:2025.10.12"

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom-remap", version = "1.14-SNAPSHOT" }
